[package]
name = "tantivy-bench"
version = "0.1.0"
authors = ["Jason Wolfe"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tantivy = {git = "https://github.com/quickwit-inc/tantivy.git", rev="7f9627c78409df571c9784d3e6ccc550464d877c"}
env_logger = "0.5"
futures = "*"

[profile.release]
lto = true
opt-level = 3
overflow-checks = false
# debug-assertions = false
